# Generated by Django 3.2 on 2021-07-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizapplication',
            name='question',
            field=models.TextField(),
        ),
    ]
